### PR TITLE
Properly License/Attribute audio samples

### PR DESCRIPTION
**Pull request by ghindman**
The wav files in the /samples directly need to be properly licensed and attributed as derivative works under CC-BY-SA 4.0.  This pull request the proper license file in the samples directory.

### CODE REVIEW

**Comment by ghindman** [comment]
@vcgomes can you please review and ensure I have attributed the source correctly?

**Comment by vcgomes** [comment]
The attribution looks right.

I will only suggest squashing those four commits into a single one.

**Comment by ghindman** [comment]
Yeah, looked like the squash could only be done on the merge side, no?

**Comment by keerockl** [comment]
squash/merge is done.

**Pull request merged**
