### PR TITLE
GitHub next

### PR DESCRIPTION
**Pull request by edersondisouza**
This patch should bring the `next` branch into master. The patches were already reviewed to enter `next`, but as I solved some (small) conflicts when rebasing, maybe some caution is necessary.

The `next` branch contains v-streaming new features: gstreamer plugin for demonstration and multi-client handling.

### CODE REVIEW

**Comment by tvyas** [comment]
Just checking - was it intentional to leave out the top 3 commits from the next branch ?

**Comment by edersondisouza** [comment]
> Just checking - was it intentional to leave out the top 3 commits from the next branch ?

Ohhh... nice catch! I'll update. (If you can get to have #37 merged on next really soon, I can also add those patches in this PR.)

**Comment by tvyas** [comment]
> > Just checking - was it intentional to leave out the top 3 commits from the next branch ?
> 
> Ohhh... nice catch! I'll update. (If you can get to have #37 merged on next really soon, I can also add those patches in this PR.)

Right, let me find someone who can do it today.

**Comment by edersondisouza** [comment]
v2: Added missing commits from `next` branch, as well as new commits coming from #37.

**Review by tvyas — APPROVED** [review]

**Pull request merged**
