### PR TITLE
Docs: Updating keywords and cleanup images

### PR DESCRIPTION
**Pull request by sbhendig**
Signed-off-by: Swetha Bhendigeri <swetha.bhendigeri@intel.com>

### CODE REVIEW

**Review by tvyas — COMMENTED** [review]
Looks like, 
public/doc/images/icd_example_system_video1.png and public/doc/images/icd_example_system_video2.png
don't have any the keyword being replaced here.

Also, public/doc/images/icd_mediatransport_subsystem.png needs to be edited seperately.

**Comment by edersondisouza** [comment]
What did change in the images? (I've seen only one image different, but several are changed.)
I guess you could squash the two commits, no?

**Comment by sbhendig** [comment]
@ederson - can we squash and merge these 2 commits using the built-in option.

**Review by edersondisouza — APPROVED** [review]
Let's hope this "squash button" works.

**Comment by sbhendig** [comment]
once you  can give me thumbs up, we can squash and merge these 2 commits

**Comment by edersondisouza** [comment]
I already approved, but if you really want it, :+1:

**Pull request merged**
